### PR TITLE
Additions, docs & fixes

### LINKED ISSUE #5: Calling Room.Doors causes StackOverflowError
[2025-02-11 21:14:55.140 +01:00] [ERROR] [LabApi] 'StackOverflowException' occured while invoking 'OnPlayerHurting' on 'AntiSuicidalZombies.MainClass': 'The requested operation caused a stack overflow.', stack trace:
                                   at LabApi.Features.Wrappers.Room.get_Doors () [0x00000] in <c20488a5a42a492c931d89475bee91cb>:0 
                                   at LabApi.Features.Wrappers.Room.get_Doors () [0x00000] in <c20488a5a42a492c931d89475bee91cb>:0 
                                   at LabApi.Features.Wrappers.Room.get_Doors () [0x00000] in <c20488a5a42a492c931d89475bee91cb>:0

### PR DESCRIPTION
**Pull request by Misfiy**
Resolves #5

### CODE REVIEW

**Comment by Misfiy** [comment]
YIPPIE!

**Comment by Misfiy** [comment]
TLDR i got bored and i didnt like it

**Review by davidsebesta1 — CHANGES_REQUESTED** [review]
Nice job 👍 . Just check what I said about the position & rotation

File: LabApi/Features/Wrappers/Players/Player.cs [hunk 1]
```diff
@@ -661,19 +661,8 @@ public Player? DisarmedBy
...
-                return Vector3.zero;
-            }
-
-            return fpcRole.FpcModule.Position;
-        }
-        set
-        {
-            ReferenceHub.TryOverridePosition(value);
-        }
+        get => ReferenceHub.roleManager.CurrentRole is not IFpcRole fpcRole ? Vector3.zero : fpcRole.FpcModule.Position;
```
[the remark this answers is not in the document]
Comment (Misfiy) [reply LabApi/Features/Wrappers/Players/Player.cs:664]: I'm not sure which would be better, but I can revert it if you want

[the remark this answers is not in the document]
Comment (Misfiy) [reply LabApi/Features/Wrappers/Players/Player.cs]: Reverted

File: LabApi/Features/Wrappers/Facility/Rooms/Room.cs [hunk 2]
```diff
@@ -76,39 +76,21 @@ internal virtual void OnRemoved()
...
+    /// Gets the doors that are a part of this room. TODO: Cache in base game code?
     /// </summary>
-    public IEnumerable<Door> Doors
-    {
-        get
-        {
-            return Doors.Where(n => n.Rooms.Contains(Base)); // TODO: Cache the result in base game code?
-        }
-    }
+    public IEnumerable<Door> Doors => Door.List.Where(d => d.Rooms.Contains(Base));
```
Comment (Misfiy) [inline LabApi/Features/Wrappers/Facility/Rooms/Room.cs:81]: (fix: no more stackoverflow)

**Comment by ced777ric** [comment]
Could you change your PR to target `dev` instead?

File: LabApi/Features/Wrappers/Facility/Hazards/Tesla.cs [hunk 3]
```diff
@@ -86,21 +86,18 @@ public float InactiveTime
         /// Returns if any <see cref="Player"/> is in range where tesla gate starts idling.
         /// </summary>
         /// <returns>Whether any player is within the idle range.</returns>
-        public bool IsAnyPlayerInIdleRange() => HashsetExtensions.Any(ReferenceHub.AllHubs, Base.IsInIdleRange);
+        public bool IsAnyPlayerInIdleRange() => ReferenceHub.AllHubs.Any(Base.IsInIdleRange);
```
Comment (ced777ric) [inline LabApi/Features/Wrappers/Facility/Hazards/Tesla.cs:89]: Is this using normal Linq?
The goal of the HashsetExtensions was to avod alloc'ing (linq does this)

File: LabApi/Features/Wrappers/Facility/Rooms/LightsController.cs [hunk 4]
```diff
@@ -38,10 +38,11 @@ internal static void Initialize()
             RoomLightController.OnAdded += (roomLightController) => _ = new LightsController(roomLightController);
             RoomLightController.OnRemoved += (roomLightController) => Dictionary.Remove(roomLightController);
         }
+
         /// <summary>
         /// The base game object.
         /// </summary>
-        public RoomLightController Base { get; private set; }
+        public RoomLightController Base { get; }
```
Comment (ced777ric) [inline LabApi/Features/Wrappers/Facility/Rooms/LightsController.cs:45]: Shouldnt the setter be private in this context?
Or does this not apply to constructors?

**Review by ced777ric — CHANGES_REQUESTED** [review]

File: LabApi/Features/Wrappers/Facility/Hazards/Tesla.cs (hunk 3 above)
Comment (Misfiy) [reply LabApi/Features/Wrappers/Facility/Hazards/Tesla.cs:89]: image

**Review by ced777ric — APPROVED** [review]
